# Generated by Django 4.1.4 on 2022-12-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gms', '0004_auto_20170421_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='location',
            field=models.CharField(default='Main Campus', max_length=30),
        ),
    ]
